[package]
name = "nrtrt"
version = "0.1.0"
authors = ["Łukasz <krawacik3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
minifb = "0.13.0"
rand = "0.7.2"
image = "0.22.3"